electron/sheriff

package.json
src/MessageBuilder.ts
src/helpers.ts
src/index.ts
src/octokit.ts
src/permissions/run.ts
yarn.lock

This had the unfortunate side effect of octokit being annoying af and needing to be upgraded

feat: use graphql for team member listing to avoid child teams

---

src/permissions/run.ts

As in title, switches from only supporting `read | write | admin` to `read | triage | write | maintain | admin`.
This is the first step towards custom roles support

feat: add support for triage/maintain roles

---

package.json
src/index.ts
src/octokit.ts
tsconfig.json
yarn.lock

As in title, may `electron-bot` slowly be murdered but in a nice way 😆

refactor: use GH app instead of a magic super token

---

package.json
src/permissions/run.ts
yarn.lock

This drops the run time of Electrons Sheriff run from 130 seconds to 25

perf: fetch a bunch of repo data before running checks

---

.github/workflows/lint.yml
package.json
src/MessageBuilder.ts
src/helpers.ts
src/index.ts
src/octokit.ts
src/permissions/run.ts
yarn.lock

Add lint-staged as a precommit hook.

chore: add linting

---

app.json
package.json
src/MessageBuilder.ts
src/constants.ts
src/index.ts
src/octokit.ts
src/permissions/plugins/gsuite/auth.ts
src/permissions/plugins/gsuite/index.ts
src/permissions/plugins/index.ts
src/permissions/plugins/slack/index.ts
src/permissions/run.ts
yarn.lock

As in title. Needs update to graphql portion still.

refactor: migrate to GitHub app for Heroku usage

---

README.md

These got added a while back so just documenting them.

docs: add triage and maintain roles to config example

---

src/permissions/run.ts

Lint has been failing on `main`, so fix it up.

chore: run prettier so lint check is happy

---

README.md

docs: remove outdated create repo limitation

---

.dockerignore
Dockerfile
Makefile
package.json
src/index.ts

Adds a Dockerfile and the usual scaffolding for building/running this within a container. 
Oh and sneaks in support for stopping the server with CTRL+C. :)

feat: add container support

---

README.md
package.json
src/octokit.ts
src/permissions/generate.ts
src/permissions/level-converters.ts
src/permissions/plugins/Plugin.ts
src/permissions/plugins/gsuite/index.ts
src/permissions/plugins/slack/index.ts
src/permissions/run.ts
src/permissions/types.ts
yarn.lock

This is stacked on #26 for use of the read-only octokit helper
Closes #16

feat: add a new generate script to create an initial config file base

---

README.md
package.json
src/constants.ts
src/octokit.ts
yarn.lock

Signed-off-by: Jeffrey Sica <me@jeefy.dev>
cc @marshallofsound

fix: docs update, doc additional env vars

---

Makefile

Whoops 
Signed-off-by: Jeffrey Sica <me@jeefy.dev>

fix: remove artifact from my copy-pasta Makefile ;)

---

README.md
src/constants.ts
src/permissions/run.ts

Probably makes sense if we want to support PR checks using Sheriff (which I'm currently working towards) 
cc @MarshallOfSound

Add branch support

---

src/index.ts

🙃 300 slack notifications are fun, but like, annoying

fix: handle org owners in collaborator permission change events

---

README.md

Refs https://github.com/electron/sheriff/blob/47cc4cc3dc3caf91b5cc7f1ad031d8347de77ddc/src/permissions/run.ts#L117-L119

docs: document repository settings key

---

src/permissions/plugins/gsuite/auth.ts
src/permissions/run.ts

Refs https://github.com/electron/electron/pull/38452

chore: `process.mainModule` -> `require.main`

---

.github/workflows/lint.yml
package.json
src/permissions/run.ts
src/permissions/types.ts
yarn.lock

feat: support custom repo properties

---

src/MessageBuilder.ts
src/index.ts
src/permissions/run.ts
src/permissions/types.ts

Would recommend viewing with whitespace turned off, wraps a bunch of stuff in for-loops

feat: support multiple orgs

---

src/permissions/run.ts

Avoids duplicating team lists across org configurations, this allows us to do:
```
- name: wg-ecosystem
reference: electron/wg-ecosystem
```
And have another org have a team identically configured to the ecosystem wg team in the electron org

feat: add support for cross-org team references

---

.gitignore
src/helpers.ts
src/permissions/run.ts

* Fixes some bugs with multi-org
* Invites folks missing from the org, to the org

feat: add support for sheriff inviting users to org

---

package.json
src/MessageBuilder.ts
src/ambient.d.ts
src/constants.ts
src/dry-run-q.ts
src/index.ts
src/permissions/run.ts
yarn.lock

Closes #29
This runs a PR dry run check against the `.permissions` repo on every PR

feat: add sheriff dry run

---

src/index.ts

fix: use updated merge commit sha instead of unknown one

---

.github/workflows/lint.yml
.github/workflows/test.yml
package.json
src/permissions/ruleset.ts
src/permissions/run.ts
src/permissions/types.ts
yarn.lock

Should make sheriff chill out a bit 😅

fix: ensure rulesets dont have constant drift to fix

---

src/MessageBuilder.ts
src/index.ts

Modifications to rulesets at repo or org level should be alerted on

feat: monitor rulesets via webhook

---

src/permissions/run.ts

As in title, fixes an issue where there was a 'difference' caused by default values

fix: account for default values when diffing props
